# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UberOAuth' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

    pod 'UberKit'
    
  # Pods for UberOAuth

  target 'UberOAuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
