# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'UberOAuth' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UberOAuth
  #  pod 'Scenario', '0.0.1-beta'
  pod 'Scenario/UberOAuth', :path => '../Scenario.podspec'

  target 'UberOAuthTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
